---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
